tellerops/teller

README.md
pkg/core/types.go
pkg/providers/hashicorp_vault.go
pkg/providers/hashicorp_vault_test.go
pkg/teller.go
pkg/teller_test.go

- Add support in `HashicorpVault.GetMapping()` and `HashicorpVault.Get()` to handle provider responses which may have either `data.data{}` or `data{}`. This enables support for the Hashicorp Vault dynamic secrets backend.
- Add the ability to remap keys from providers to different local environment variable keys when using `env_sync`. This allows mapping the hashicorp vault response for dynamic secrets to the correct postgres username and password environment variables. Vault will always return `data{username: '<user>', password: '<pass>'`, however postgres expects `PGUSER` and `PGPASSWORD`. With remapping we can set `PGUSER = username` and `PGPASSWORD = password`.
Resolves #4

Add support for hashicorp vault dynamic database secrets

---

README.md

Update the `teller run` docs to include `--` to ensure flags are passed to child process
Resolves #6

Fix teller run child process docs to pass flags

---

main.go

The `redact` command help was outputting the `scan` command's output

Fixing redact command help msg

---

main.go

Hey @jondot, 
I have added two minor changes:
- Unexpected behavior when `teller new` command runs once `.teller` file exists
- If `.teller` file already exists and the `new `command is given, check with the user if he wants to override the existing configuration

Make new command more friendly

---

pkg/providers/dotenv.go

Currently, for the `dotenv` provider, in order to do `Put` the file must actually exist. This pull request fixes such behavior, to be consistent with other providers:
- ensure that all subdirectories exist
- ensure that file exist
Resolves #54 
```go
func main() {
providers := tellerpkg.BuiltinProviders{}
provider, err := providers.GetProvider("dotenv")
if err != nil {
panic(err)
}
key := core.KeyPath{
Path:  "/tmp/foo/bar.env",
Field: "data",
}
val := `{"key": "true"}`
err = provider.Put(key, val)
if err != nil {
panic(err)
}
// Get
entry, err := provider.Get(key)
if err != nil {
panic(err)
}
log.Printf("%+v\n", entry)
}
```

Handle non-existing dotenv file while doing `Put`

---

README.md
pkg/providers/aws_secretsmanager.go
pkg/providers/dotenv.go
pkg/providers/mock_providers/aws_secretsmanager_mock.go
pkg/utils/strings.go

Hi,
As we need badly the `Put` and `PutMapping` functionality for AWS Secrets Manager, this pull request brings such functionality. Hope you'll like it! 🙂 
**NOTE:** I saw an open pull request #47 from @JacobJohansen, which, among other things, also implements the `Put` for AWS Secrets Manager.
However, this PR doesn't bring upsert behavior to the `Put` and `PutMapping` methods, and as discussed on #54, such behavior is expected. 
Also, I saw some failing tests and inactivity on that pull request, that's why I created another PR.  But, I will be happy to rebase my changes to the Jacob's branch, if #47 is going to be fixed and merged soon 🙂  Regardless the option, Jacob's pull request still introduces something more - `Put` method implementation for AWS SSM, so our PRs don't overlap in …

Implement AWS Secrets Manager `Put` and `PutMapping` as upsert

---

README.md
main.go
pkg/porcelain.go
pkg/teller.go
pkg/teller_test.go

This pull request supports the following `delete` scenarios:
- Delete keys based on mapping in config
- Delete keys by secret path
- Delete all keys based on path
I also updated the documentation and wrote basic tests for different delete cases.
~**NOTE: Do not merge it yet:** This PR depends on #60. Once the #60 is reviewed, approved and merged, I will rebase this one.~ PR #60 has been successfully merged, and this PR has been rebased to the latest `master`.
Resolves #57 
```bash
cat > ./.teller.yml << ENDOFFILE
project: sample
opts: {}
prefix:
stage: development
providers:
dotenv:
env_sync:
path: ~/my-dot-env2.env
env:
FOO:
path: ~/my-dot-env.env
BAR:
path: ~/my-dot-env.env
BAZ:
path: ~/my-dot-env.env
ENDOFFILE
go run ./main.go put FOO=foo --providers=dotenv
go run ./main.go put BAR=bar …
```

Introduce Teller `delete` command 

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new_provider.md
.github/pull_request_template.md

Add GitHub templates:
1. `Bug Report` -> template for each new bug report. Ticket automatic labels as `bug` 
2. `Feature Request` -> template when want to request a new feature. Ticket automatic labels as `enhancement`
3. `Adding new provider` -> template when users requested a new provider. Ticket automatic labels as `new-provider`
4. `Pull request`-> template for new pull request
Let me know if you have more template suggestions

adding github templates

---

.github/workflows/release.yaml
.gitignore
.goreleaser.yml

Adding CD to our workflows for releasing new Teller version by git tagging command:
```sh
git tag v... && git push origin v...
```
I have adde `ldflags` flag to `.goreleaser.yml` for inject the the version details.
we need to add `GORELEASER_GITHUB_TOKEN` to settings
Easy way to release new Teller versions
This command was run on my local computer
```sh
goreleaser release --snapshot --rm-dist
```

add goreleaser to ci step

---

main.go

When using `teller v` the version should be printed however i got this instead
```
teller: error: unexpected argument v, did you mean one of "version", "sh", "env"?
```
And by checking the code I found that `aliases` needs to be used instead of `short` (as teller doesn't have `-v` anyway)
The `help` message will be changed into the mentioned below, which indicates that `version` has a short-hand called `v`
```
version (v)
Teller version
```

fix: use aliases key instead of short for version cmd

---

main.go
pkg/core/types.go
pkg/teller.go
pkg/teller_test.go

No specific issue
The changes contain adding Teller the ability to sort its entries by ProviderName (in-case-sensitive) and use this ability only in the `show` command.
The reason I have added it only for the show command is that the other output formats do not print the provider at all, but a mix of all the entries from all the providers, sorted by the entry key.
The show command is the only output command which prints the provider as well.
The show command output the entries with the provider name as the leading detail for each entry.
Since the leading detail is the provider name, and the output should be sorted as in the other output format, I think it is better to sort by provider name.
All the entries within every provider would be sorted by key - ascending.
Tested manually, with 4 …

Group show command output by provider name

---

README.md
pkg/providers.go
pkg/providers/filesystem.go
pkg/providers/filesystem_test.go
pkg/wizard_template.go

Create filesystem provider
```
.
└── tmp/filesystem-provider
├── settings/
│   ├── billing-svc
│   └── all/
│       ├── entry-a
│       ├── entry-b
│       └── entry-c
|
└── entry
```
```yaml
providers:
filesystem:
env_sync:
path:  /tmp/filesystem-provider/settings
env:
ETC_DSN:
path: /tmp/filesystem-provider/entry
ETC_DSN2:
path: /tmp/filesystem-provider/path/test/entry
```
1. Update existing file
```sh
go run main.go put ETC_DSN=new-entry-value --providers filesystem
```
2. Creating recursively entry
In this example the path `/tmp/filesystem-provider/path/test/entry` not exists (see file structure example), the file `entry` will create under `path`, `test` folders (event if the folders not exists)
```sh
go run main.go put ETC_DSN2=new-entry-value --providers filesystem
```
3. with …

add filesystem provider

---

e2e/tests/put.yml
pkg/teller.go

Signed-off-by: Elad Kaplan <kaplan.elad@gmail.com>
sort put command values for keep porcelain stdout consistent

sort put command values for keep porcelain stdout consistent

---

e2e/README.md
e2e/e2e_test.go
e2e/tests/scan.yml
e2e/testutils/config.go
pkg/porcelain.go

Add `scan` e2e test. Scan test has a dynamic response by presenting the scan time. To compare the STDOUT I have added `replace_stdout_content` field to the e2e yaml configuration, which allows us to replace with regex dynamic content.
coverage more Teller command

add scan command to e2e tests

---

pkg/core/populate.go
pkg/core/populate_test.go
pkg/wizard_template.go

#29 
Adding the option to set default values for `ops` if the value not found from environment variable.
@jondot, this convention `:default:{XX}` is the best I can think. fell free to suggest another one.

Default value for opts

---

pkg/providers/aws_secretsmanager.go

#113 113
Fix error when number return from the provider
```
could not load all variables from the given existing providers error="json: cannot unmarshal number into Go value of type string"
```

fix unmarshal number into string

---

pkg/providers/hashicorp_vault.go

#115
Fix run time error when secret not found
Created a yaml file with incorrect file path:
```sh
panic: runtime error: invalid memory address or nil pointer dereference
...
```

fix runtime error when vault path not found

---

pkg/providers/aws_secretsmanager.go
pkg/wizard_template.go

#117 
Support fetch AWS secret by specific version
Teller yaml config
```yaml
providers:
aws_secretsmanager:
```

support fetch AWS secret by specific version

---

e2e/tests/sh.yml
pkg/teller.go
pkg/teller_test.go

#131
For shell print export:
- Enclosing secret in single quote
- Support password with single quotes too
Passwords containing special characters are now supported.
e2e + unit test + manual tests

Support special characters in teller sh

---

README.md
pkg/providers.go
pkg/providers/process_env.go
pkg/providers/process_env_test.go
pkg/wizard_template.go

https://github.com/tellerops/teller/issues/116
Add `process_env` provider.  Load the environment variables from the parent process as needed.
```yaml
providers:
process_env:
env_sync:
env:
ETC_DSN:
```

Add process_env provider

---

pkg/providers/process_env.go

The last merge to master broke `process_env` provider, most likely a copy/paste error. 
Merge: https://github.com/tellerops/teller/commit/783dc56

Fix from merge 783dc56 to process_env provider

---

pkg/providers/aws_secretsmanager.go
pkg/providers/aws_ssm.go

#134 
Add environment variable to allow custom aws endpoint for aws providers to work with localstack
Allow developers to use services locally that we use for our deployed environments
Tested against localstack when `AWS_ENDPOINT` environment variable is set.
Tested against live aws when `AWS_ENDPOINT` environment variable is absent

GH-134: localstack compatibility for aws providers

---

pkg/integration_test/consul_test.go
pkg/integration_test/dotenv_test.go
pkg/integration_test/etcd_test.go
pkg/integration_test/heroku_test.go
pkg/integration_test/vault_test.go

`make integration_api` fails with this error message.
```
$ make integration_api
go test -v ./pkg/integration_test -cover -tags="integration_api integration"
pkg/integration_test/consul_test.go:60:12: not enough arguments in call to providers.NewConsul
have ()
want ("github.com/spectralops/teller/pkg/logging".Logger)
pkg/integration_test/dotenv_test.go:27:12: not enough arguments in call to providers.NewDotenv
have ()
want ("github.com/spectralops/teller/pkg/logging".Logger)
pkg/integration_test/etcd_test.go:64:12: not enough arguments in call to providers.NewEtcd
have ()
want ("github.com/spectralops/teller/pkg/logging".Logger)
pkg/integration_test/heroku_test.go:38:12: not enough arguments in call to providers.NewHeroku
have ()
want ("github.com/spectralops/teller/pkg/logging".Logger) …
```

Fix integration test

---

e2e/tests/redact.yml
e2e/tests/run-redact.yml
pkg/redactor.go
pkg/redactor_test.go
pkg/teller.go
pkg/teller_test.go

This PR fixes the issue that teller doesn’t output anything until the child process ends if  `--reduct` is given.
This issue happens because `Teller.execCmd` calls `CombinedOutput`, which keeps outputs on RAM until the child process ends:
https://github.com/tellerops/teller/blob/922b8919390989e33ef7366013eb122215eea25a/pkg/teller.go#L76-L81
If the child process ends soon, it won't be a problem. However, if the process is a long-running program such as a server, teller never outputs anything. What is worse, it'll use up RAM and be killed at some point, or panic with `ErrTooLarge` (see also https://pkg.go.dev/bytes#Buffer.Write).
This PR rewrites `Redactor` to work as an adapter of `io.Writable`. This implementation writes output immediately to stdout and stderr, and doesn't consume RAM.
If …

Fix no redacted output until process ends

---

pkg/core/populate.go
pkg/core/populate_test.go
pkg/teller.go
pkg/teller_test.go

It'd be nice if `{{project}}` is substituted with the project name.
We store secrets in etcd with the following path rule: `/{project name}/{stage}/{secret name}`, and thus our `.teller.yml` looks like this:
```yaml
project: some service
opts:
project: some service
stage: development
providers:
etcd:
env_sync:
path: /{{project}}/{{stage}}/
```
It works, but `opts.project` is redundant because it's always the same as `project`. 
If `{{project}}` is substituted with the top-level `project` value, that'd be helpful.
This PR also refactors `core.Populate` so that it computes the substitution rules in advance. `Populate.KeyPath` is called multiple times, and it computes the same substitution rules. It's better to compute the rules only one time in the constructor.
I run a benchmark test with …

substitute {{project}} with the project name

---

main.go

https://github.com/tellerops/teller/issues/162
https://github.com/tellerops/teller/issues/162
In case, we use hardcoded default `.teller.yml` config and the file doesn't exist, try to find `.yaml` version.
In case, that the `.teller.yml` was set explicitly, won't. 
It's in the issue.
tl;dr: official YAML extenstion is `*.yaml`. Yet, for backward compatibility, we need to try `*.yml` first.
Some people, like me, can prefere `*.yaml` extension and don't want to set the config explicitly.
I did manual testing. Really not sure how to do some unit testing in main func.
Yet the change is really straight forward.

fallback default ''.teller.yml' to '.teller.yaml'

---

pkg/providers/keypass.go

Keepass provider entries in root of database should be created without leading slash
for consistency between root and non-root Keepass items
Inconsistent path creates confusion and it made me think that Keepass
support is broken, because path to entry was not predictable.
Created Keepass database with entries in root and inside groups.
Both should have path without need for leading slash. E.g. 
```
KeyPass:
env:
world:
path: Root/hello
redis:
path: Root/redis/config/foobar
```
Please consider this change.

keepass: unexpected leading slash for root items

---

README.md
pkg/core/types.go
pkg/providers/aws_secretsmanager.go
pkg/providers/aws_secretsmanager_test.go
pkg/providers/helpers_test.go

in addition to the key/value pair secrets
currently AWS Secret Manager only supports key/value pair secrets
this PR adds the ability to define a secret as being plaintext which is common when using secrets for things like files
supports fetching plaintext secrets from AWS Secret Manager which are currently not supported
I tested it against AWS Secrets Manager

feat: add support for AWS SM plaintext secrets

---

main.go

N/A
For new users, if you just run `teller` with no arguments the output is not very intuitive. This PR simply displays the `--help` message if you run `teller` without arguments.
Makes `teller` a little bit more user friendly.
Local testing.

fix: display help if no args provided
